// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:82e557b2-10b0-492f-b210-4268848bcfe4",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_E9YX0WGXa",
    "aws_user_pools_web_client_id": "5dao7ul0kask07295kdhcqf561"
};


export default awsmobile;
